// Generated by gencpp from file visp_ros/BlobTracker.msg
// DO NOT EDIT!


#ifndef VISP_ROS_MESSAGE_BLOBTRACKER_H
#define VISP_ROS_MESSAGE_BLOBTRACKER_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <geometry_msgs/PoseStamped.h>
#include <sensor_msgs/Image.h>
#include <visp_ros/ImagePoint.h>
#include <visp_ros/ProjectedPoint.h>

namespace visp_ros
{
template <class ContainerAllocator>
struct BlobTracker_
{
  typedef BlobTracker_<ContainerAllocator> Type;

  BlobTracker_()
    : pose_stamped()
    , image()
    , blob_cogs()
    , blob_proj()  {
    }
  BlobTracker_(const ContainerAllocator& _alloc)
    : pose_stamped(_alloc)
    , image(_alloc)
    , blob_cogs(_alloc)
    , blob_proj(_alloc)  {
  (void)_alloc;
    }



   typedef  ::geometry_msgs::PoseStamped_<ContainerAllocator>  _pose_stamped_type;
  _pose_stamped_type pose_stamped;

   typedef  ::sensor_msgs::Image_<ContainerAllocator>  _image_type;
  _image_type image;

   typedef std::vector< ::visp_ros::ImagePoint_<ContainerAllocator> , typename ContainerAllocator::template rebind< ::visp_ros::ImagePoint_<ContainerAllocator> >::other >  _blob_cogs_type;
  _blob_cogs_type blob_cogs;

   typedef std::vector< ::visp_ros::ProjectedPoint_<ContainerAllocator> , typename ContainerAllocator::template rebind< ::visp_ros::ProjectedPoint_<ContainerAllocator> >::other >  _blob_proj_type;
  _blob_proj_type blob_proj;





  typedef boost::shared_ptr< ::visp_ros::BlobTracker_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::visp_ros::BlobTracker_<ContainerAllocator> const> ConstPtr;

}; // struct BlobTracker_

typedef ::visp_ros::BlobTracker_<std::allocator<void> > BlobTracker;

typedef boost::shared_ptr< ::visp_ros::BlobTracker > BlobTrackerPtr;
typedef boost::shared_ptr< ::visp_ros::BlobTracker const> BlobTrackerConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::visp_ros::BlobTracker_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::visp_ros::BlobTracker_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::visp_ros::BlobTracker_<ContainerAllocator1> & lhs, const ::visp_ros::BlobTracker_<ContainerAllocator2> & rhs)
{
  return lhs.pose_stamped == rhs.pose_stamped &&
    lhs.image == rhs.image &&
    lhs.blob_cogs == rhs.blob_cogs &&
    lhs.blob_proj == rhs.blob_proj;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::visp_ros::BlobTracker_<ContainerAllocator1> & lhs, const ::visp_ros::BlobTracker_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace visp_ros

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::visp_ros::BlobTracker_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::visp_ros::BlobTracker_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::visp_ros::BlobTracker_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::visp_ros::BlobTracker_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::visp_ros::BlobTracker_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::visp_ros::BlobTracker_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::visp_ros::BlobTracker_<ContainerAllocator> >
{
  static const char* value()
  {
    return "0dc82e760baf9b1ef9beb061604f3e2a";
  }

  static const char* value(const ::visp_ros::BlobTracker_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x0dc82e760baf9b1eULL;
  static const uint64_t static_value2 = 0xf9beb061604f3e2aULL;
};

template<class ContainerAllocator>
struct DataType< ::visp_ros::BlobTracker_<ContainerAllocator> >
{
  static const char* value()
  {
    return "visp_ros/BlobTracker";
  }

  static const char* value(const ::visp_ros::BlobTracker_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::visp_ros::BlobTracker_<ContainerAllocator> >
{
  static const char* value()
  {
    return "geometry_msgs/PoseStamped pose_stamped\n"
"sensor_msgs/Image image\n"
"ImagePoint[] blob_cogs\n"
"ProjectedPoint[] blob_proj\n"
"\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/PoseStamped\n"
"# A Pose with reference coordinate frame and timestamp\n"
"Header header\n"
"Pose pose\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Pose\n"
"# A representation of pose in free space, composed of position and orientation. \n"
"Point position\n"
"Quaternion orientation\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Point\n"
"# This contains the position of a point in free space\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Quaternion\n"
"# This represents an orientation in free space in quaternion form.\n"
"\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"float64 w\n"
"\n"
"================================================================================\n"
"MSG: sensor_msgs/Image\n"
"# This message contains an uncompressed image\n"
"# (0, 0) is at top-left corner of image\n"
"#\n"
"\n"
"Header header        # Header timestamp should be acquisition time of image\n"
"                     # Header frame_id should be optical frame of camera\n"
"                     # origin of frame should be optical center of camera\n"
"                     # +x should point to the right in the image\n"
"                     # +y should point down in the image\n"
"                     # +z should point into to plane of the image\n"
"                     # If the frame_id here and the frame_id of the CameraInfo\n"
"                     # message associated with the image conflict\n"
"                     # the behavior is undefined\n"
"\n"
"uint32 height         # image height, that is, number of rows\n"
"uint32 width          # image width, that is, number of columns\n"
"\n"
"# The legal values for encoding are in file src/image_encodings.cpp\n"
"# If you want to standardize a new string format, join\n"
"# ros-users@lists.sourceforge.net and send an email proposing a new encoding.\n"
"\n"
"string encoding       # Encoding of pixels -- channel meaning, ordering, size\n"
"                      # taken from the list of strings in include/sensor_msgs/image_encodings.h\n"
"\n"
"uint8 is_bigendian    # is this data bigendian?\n"
"uint32 step           # Full row length in bytes\n"
"uint8[] data          # actual matrix data, size is (step * rows)\n"
"\n"
"================================================================================\n"
"MSG: visp_ros/ImagePoint\n"
"# Message corresponding to vpImagePoint class\n"
"float64 i      # i (respectively v) position in the image\n"
"float64 j      # j (respectively u) position in the image\n"
"\n"
"\n"
"================================================================================\n"
"MSG: visp_ros/ProjectedPoint\n"
"# Message corresponding to coordinates of the point after perspective projection\n"
"float64 x      # Coordinate of the point in the image plane in meter along X axis\n"
"float64 y      # Coordinate of the point in the image plane in meter along Y axis\n"
"\n"
;
  }

  static const char* value(const ::visp_ros::BlobTracker_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::visp_ros::BlobTracker_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.pose_stamped);
      stream.next(m.image);
      stream.next(m.blob_cogs);
      stream.next(m.blob_proj);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct BlobTracker_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::visp_ros::BlobTracker_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::visp_ros::BlobTracker_<ContainerAllocator>& v)
  {
    s << indent << "pose_stamped: ";
    s << std::endl;
    Printer< ::geometry_msgs::PoseStamped_<ContainerAllocator> >::stream(s, indent + "  ", v.pose_stamped);
    s << indent << "image: ";
    s << std::endl;
    Printer< ::sensor_msgs::Image_<ContainerAllocator> >::stream(s, indent + "  ", v.image);
    s << indent << "blob_cogs[]" << std::endl;
    for (size_t i = 0; i < v.blob_cogs.size(); ++i)
    {
      s << indent << "  blob_cogs[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::visp_ros::ImagePoint_<ContainerAllocator> >::stream(s, indent + "    ", v.blob_cogs[i]);
    }
    s << indent << "blob_proj[]" << std::endl;
    for (size_t i = 0; i < v.blob_proj.size(); ++i)
    {
      s << indent << "  blob_proj[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::visp_ros::ProjectedPoint_<ContainerAllocator> >::stream(s, indent + "    ", v.blob_proj[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // VISP_ROS_MESSAGE_BLOBTRACKER_H
