// Generated by gencpp from file visp_ros/PoseStampedStatus.msg
// DO NOT EDIT!


#ifndef VISP_ROS_MESSAGE_POSESTAMPEDSTATUS_H
#define VISP_ROS_MESSAGE_POSESTAMPEDSTATUS_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <geometry_msgs/PoseStamped.h>

namespace visp_ros
{
template <class ContainerAllocator>
struct PoseStampedStatus_
{
  typedef PoseStampedStatus_<ContainerAllocator> Type;

  PoseStampedStatus_()
    : status(0)
    , pose_stamped()  {
    }
  PoseStampedStatus_(const ContainerAllocator& _alloc)
    : status(0)
    , pose_stamped(_alloc)  {
  (void)_alloc;
    }



   typedef int8_t _status_type;
  _status_type status;

   typedef  ::geometry_msgs::PoseStamped_<ContainerAllocator>  _pose_stamped_type;
  _pose_stamped_type pose_stamped;





  typedef boost::shared_ptr< ::visp_ros::PoseStampedStatus_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::visp_ros::PoseStampedStatus_<ContainerAllocator> const> ConstPtr;

}; // struct PoseStampedStatus_

typedef ::visp_ros::PoseStampedStatus_<std::allocator<void> > PoseStampedStatus;

typedef boost::shared_ptr< ::visp_ros::PoseStampedStatus > PoseStampedStatusPtr;
typedef boost::shared_ptr< ::visp_ros::PoseStampedStatus const> PoseStampedStatusConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::visp_ros::PoseStampedStatus_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::visp_ros::PoseStampedStatus_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::visp_ros::PoseStampedStatus_<ContainerAllocator1> & lhs, const ::visp_ros::PoseStampedStatus_<ContainerAllocator2> & rhs)
{
  return lhs.status == rhs.status &&
    lhs.pose_stamped == rhs.pose_stamped;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::visp_ros::PoseStampedStatus_<ContainerAllocator1> & lhs, const ::visp_ros::PoseStampedStatus_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace visp_ros

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::visp_ros::PoseStampedStatus_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::visp_ros::PoseStampedStatus_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::visp_ros::PoseStampedStatus_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::visp_ros::PoseStampedStatus_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::visp_ros::PoseStampedStatus_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::visp_ros::PoseStampedStatus_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::visp_ros::PoseStampedStatus_<ContainerAllocator> >
{
  static const char* value()
  {
    return "71ae8a9e7c5c6a036498a62872a0dbc4";
  }

  static const char* value(const ::visp_ros::PoseStampedStatus_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x71ae8a9e7c5c6a03ULL;
  static const uint64_t static_value2 = 0x6498a62872a0dbc4ULL;
};

template<class ContainerAllocator>
struct DataType< ::visp_ros::PoseStampedStatus_<ContainerAllocator> >
{
  static const char* value()
  {
    return "visp_ros/PoseStampedStatus";
  }

  static const char* value(const ::visp_ros::PoseStampedStatus_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::visp_ros::PoseStampedStatus_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int8 status\n"
"geometry_msgs/PoseStamped pose_stamped\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/PoseStamped\n"
"# A Pose with reference coordinate frame and timestamp\n"
"Header header\n"
"Pose pose\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Pose\n"
"# A representation of pose in free space, composed of position and orientation. \n"
"Point position\n"
"Quaternion orientation\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Point\n"
"# This contains the position of a point in free space\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Quaternion\n"
"# This represents an orientation in free space in quaternion form.\n"
"\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"float64 w\n"
;
  }

  static const char* value(const ::visp_ros::PoseStampedStatus_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::visp_ros::PoseStampedStatus_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.status);
      stream.next(m.pose_stamped);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct PoseStampedStatus_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::visp_ros::PoseStampedStatus_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::visp_ros::PoseStampedStatus_<ContainerAllocator>& v)
  {
    s << indent << "status: ";
    Printer<int8_t>::stream(s, indent + "  ", v.status);
    s << indent << "pose_stamped: ";
    s << std::endl;
    Printer< ::geometry_msgs::PoseStamped_<ContainerAllocator> >::stream(s, indent + "  ", v.pose_stamped);
  }
};

} // namespace message_operations
} // namespace ros

#endif // VISP_ROS_MESSAGE_POSESTAMPEDSTATUS_H
